# Generated by Django 3.0.2 on 2020-01-12 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200112_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Comments'),
        ),
    ]
